### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by realies** [tomek-l/pms7003#3]
Trying to read the sensor with the example code but getting 'Connection problem', how should one debug? Getting a fan spin on the sensor and serial is enable on the RPi connected to it.

**Comment by tomasz-lewicki** [comment]
Hi @realies ,

That's an interesting issue. It means that a data frame was received, but either:
- the length is incorrect
- the checksum is incorrect

Do you get it just once, or every time you're trying to call ```.read()```?

Could you tell me what's your hardware & software setup? (i.e. which Raspberry Pi and which version of Raspbian). I know that some versions had different UART device name (e.g. ```/dev/ttyAMA0```)
